# Pre-commit configuration for Python projects
repos:
  # Hooks básicos para archivos en general
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace        # Elimina espacios en blanco al final de líneas
      - id: end-of-file-fixer         # Asegura que archivos terminen con nueva línea
      - id: check-yaml                # Verifica sintaxis de archivos YAML
      - id: check-json                # Verifica sintaxis de archivos JSON
      - id: check-toml                # Verifica sintaxis de archivos TOML
      - id: check-merge-conflict      # Detecta marcadores de merge conflict
      - id: check-added-large-files   # Previene archivos grandes (>500kB)
      - id: debug-statements          # Detecta declaraciones de debug (pdb, etc)

  # Ruff: Linter y formateador todo-en-uno (reemplaza black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      # Ejecutar el linter de Ruff
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Ejecutar el formateador de Ruff
      - id: ruff-format
